name: govcookiecutter deploy documentation and skeleton package

on:
  release:
    types: [ released ]

jobs:
  deploy-documentation-package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements, and build documentation
        run: make docs
      - name: Build skeleton package
        run: python setup.py build_package
      - name: Publish to GitHub Pages
        if: startsWith(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/_build
      - name: Publish skeleton package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
